import Head from "next/head";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/Script";
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="deScription" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* <!-- Favicon --> */}
        <link href="/favicon.ico" rel="icon"></link>
        {/* <!-- Libraries Stylesheet --> */}
        <link
          href="/lib/owlcarousel/assets/owl.carousel.min.css"
          rel="stylesheet"
        ></link>
        <link href="/lib/animate/animate.min.css" rel="stylesheet"></link>

        {/* <!-- Customized Bootstrap Stylesheet --> */}
        <link href="/css/bootstrap.min.css" rel="stylesheet"></link>

        {/* <!-- Template Stylesheet --> */}
        <link href="/css/style.css" rel="stylesheet"></link>
      </Head>
      <Script
        strategy="beforeInteractive"
        src="https://code.jquery.com/jquery-3.4.1.min.js"
      ></Script>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></Script>

      <Script src="/lib/wow/wow.min.js"></Script>
      <Script src="/lib/easing/easing.min.js"></Script>
      <Script src="/lib/waypoints/waypoints.min.js"></Script>
      <Script src="/lib/counterup/counterup.min.js"></Script>
      <Script src="/lib/owlcarousel/owl.carousel.min.js"></Script>

      {/* <!-- Template JavaScript --> */}
      <Script strategy="lazyOnload" src="/js/main.js"></Script>
      <main className={styles.main}>
        <div
          id="spinner"
          class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center"
        >
          <div class="spinner"></div>
        </div>
      </main>
    </>
  );
}
