import Head from "next/head";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import Script from "next/Script";
import Facts from "@/components/Facts";
import About from "@/components/About";
import Features from "@/components/Features";
import Services from "@/components/Services";
import PricingPlan from "@/components/PricingPlan";
import Quote from "@/components/Quote";
import Testimonials from "@/components/Testimonials";
import Team from "@/components/Team";
import Blog from "@/components/Blog";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="deScription" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* <!-- Favicon --> */}
        <link href="/favicon.ico" rel="icon"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=Rubik:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
        {/* <!-- Icon Font Stylesheet --> */}
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
          rel="stylesheet"
        ></link>

        {/* <!-- Libraries Stylesheet --> */}
        <link
          href="/lib/owlcarousel/assets/owl.carousel.min.css"
          rel="stylesheet"
        ></link>
        <link href="/lib/animate/animate.min.css" rel="stylesheet"></link>

        {/* <!-- Customized Bootstrap Stylesheet --> */}
        <link href="/css/bootstrap.min.css" rel="stylesheet"></link>

        {/* <!-- Template Stylesheet --> */}
        <link href="/css/style.css" rel="stylesheet"></link>
      </Head>
      <Script
        strategy="beforeInteractive"
        src="https://code.jquery.com/jquery-3.4.1.min.js"
      ></Script>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></Script>
      <Script
        src="https://kit.fontawesome.com/a076d05399.js"
        crossorigin="anonymous"
      ></Script>
      <Script src="/lib/wow/wow.min.js"></Script>
      <Script src="/lib/easing/easing.min.js"></Script>
      <Script src="/lib/waypoints/waypoints.min.js"></Script>
      <Script src="/lib/counterup/counterup.min.js"></Script>
      <Script src="/lib/owlcarousel/owl.carousel.min.js"></Script>

      {/* <!-- Template JavaScript --> */}
      <Script strategy="lazyOnload" src="/js/main.js"></Script>
      <main>
        <Facts />
        <About />
        <Features />
        <Services />
        <PricingPlan />
        <Quote />
        <Testimonials />
        <Team />
        <Blog />
      </main>
    </>
  );
}
